# SFTP 기본 설정
sftp.host=223.39.122.217
sftp.port=40022
sftp.username=cptmap
sftp.auth-type=password

# 비밀번호 (환경 변수 SFTP_PASSWORD가 없으면 빈값)
sftp.password=${SFTP_PASSWORD:}

# 경로 및 타임아웃
sftp.remote-base-dir=/cptmap
sftp.local-base-dir=/data/batch/data/real/nugu
sftp.connect-timeout=30000
sftp.session-heartbeat=60
sftp.strict-host-key-checking=false

# 재시도 설정
sftp.retry.max-attempts=3
sftp.retry.backoff-delay=5000

# logging.level.org.apache.sshd를 DEBUG로 변경
logging.level.org.apache.sshd=DEBUG